import Head from 'next/head'
import {Layout} from 'components'

const Home: React.FC = () => {
  return (
    <div>

      <Head>
        <title>Predponta</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/logo1.ico" />
      </Head>
      <Layout/>
    </div>
  )
}
export default Home;
