export interface McaRelatorio{

    mcrCodigo?:'',
    mcrNumero?:'',
    mcrFalha?:'',
    mcrParecerTecnico?:'',
    mcrAcaoProposta?:'',
    mcrResistenciaFasesR1?:'',
    mcrResistenciaFasesR2?:'',
    mcrResistenciaFasesR3?:'',
    mcrResistenciaFasesR?:'',
    mcrResistenciaFasesStatus?:'',
    mcrImpedanciaZ1?:'',
    mcrImpedanciaZ1Status?:'',
    mcrImpedanciaZ2?:'',
    mcrImpedanciaZ2Status?:'',
    mcrImpedanciaZ3?:'',
    mcrImpedanciaZ3Status?:'',
    mcrAnguloFi1?:'',
    mcrAnguloFi2?:'',
    mcrAnguloFi3?:'',
    mcrAnguloFi?:'',
    mcrAnguloFiStatus?:'',
    mcrAnguloIf1?:'',
    mcrAnguloIf2?:'',
    mcrAnguloIf3?:'',
    mcrAnguloIf?:'',
    mcrAnguloIfStatus?:'',
    mcrResistencia?:'',
    mcrResistenciaStatus?:'',
    mcrDateInsert?:'',
    mcrUserInsert?:'',
    mcrImpedanciaL1?:'',
    mcrImpedanciaL1Status?:'',
    mcrImpedanciaL2?:'',
    mcrImpedanciaL2Status?:'',
    mcrImpedanciaL3?:'',
    mcrImpedanciaL3Status?:'',
    mcrNumeroOs?:'',
    mcrFotoCompImpedancia?:'',
    mcrFotoTendenciaAngulo?:'',
    mcrFotoTendenciaIsolamento?:'',
    mcaMedicao?: null

}