import * as Yup from 'yup'

export const validationScheme = Yup.object().shape({
   
    mcrNumero: Yup.string().trim().required("Campo obrigatório."),
    mcrFalha: Yup.string().trim().required("Campo obrigatório."),
    mcrParecerTecnico: Yup.string().trim().required("Campo obrigatório."),
    mcrAcaoProposta: Yup.string().trim().required("Campo obrigatório."),
    mcrResistenciaFasesR1: Yup.string().trim().required("Campo obrigatório."),
    mcrResistenciaFasesR2: Yup.string().trim().required("Campo obrigatório."),
    mcrResistenciaFasesR3: Yup.string().trim().required("Campo obrigatório."),
    mcrResistenciaFasesR: Yup.string().trim().required("Campo obrigatório."),
    mcrResistenciaFasesStatus: Yup.string().trim().required("Campo obrigatório."),
    mcrImpedanciaZ1: Yup.string().trim().required("Campo obrigatório."),
    mcrImpedanciaZ1Status: Yup.string().trim().required("Campo obrigatório."),
    mcrImpedanciaZ2: Yup.string().trim().required("Campo obrigatório."),
    mcrImpedanciaZ2Status: Yup.string().trim().required("Campo obrigatório."),
    mcrImpedanciaZ3: Yup.string().trim().required("Campo obrigatório."),
    mcrImpedanciaZ3Status: Yup.string().trim().required("Campo obrigatório."),
    mcrAnguloFi1: Yup.string().trim().required("Campo obrigatório."),
    mcrAnguloFi2: Yup.string().trim().required("Campo obrigatório."),
    mcrAnguloFi3: Yup.string().trim().required("Campo obrigatório."),
    mcrAnguloFi: Yup.string().trim().required("Campo obrigatório."),
    mcrAnguloFiStatus: Yup.string().trim().required("Campo obrigatório."),
    mcrAnguloIf1: Yup.string().trim().required("Campo obrigatório."),
    mcrAnguloIf2: Yup.string().trim().required("Campo obrigatório."),
    mcrAnguloIf3: Yup.string().trim().required("Campo obrigatório."),
    mcrAnguloIf: Yup.string().trim().required("Campo obrigatório."),
    mcrAnguloIfStatus: Yup.string().trim().required("Campo obrigatório."),
    mcrResistencia: Yup.string().trim().required("Campo obrigatório."),
    mcrResistenciaStatus: Yup.string().trim().required("Campo obrigatório."),
    mcrDateInsert: Yup.string().trim().required("Campo obrigatório."),
    mcrUserInsert: Yup.string().trim().required("Campo obrigatório."),
    mcrImpedanciaL1: Yup.string().trim().required("Campo obrigatório."),
    mcrImpedanciaL1Status: Yup.string().trim().required("Campo obrigatório."),
    mcrImpedanciaL2: Yup.string().trim().required("Campo obrigatório."),
    mcrImpedanciaL2Status: Yup.string().trim().required("Campo obrigatório."),
    mcrImpedanciaL3: Yup.string().trim().required("Campo obrigatório."),
    mcrImpedanciaL3Status: Yup.string().trim().required("Campo obrigatório."),
    mcrNumeroOs: Yup.string().trim().required("Campo obrigatório."),
   // mcrFotoCompImpedancia: Yup.string().trim().required("Campo obrigatório."),
   // mcrFotoTendenciaAngulo: Yup.string().trim().required("Campo obrigatório."),
   // mcrFotoTendenciaIsolamento: Yup.string().trim().required("Campo obrigatório."),
    
})