
import Head from 'next/head'
import {Menu} from 'components/layout/menu';



const Home: React.FC = () => {
  return (
    <div>

      <Head>
        <title>Predponta</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/logo1.ico" />
      </Head>
      <Menu />
      
    </div>
  )
}
export default Home;
