export interface InspecaoTermografica {

    iteCodigo?:'',
    itePosicao?:'',
    iteFase?:'',
    iteFalha?:'',
    iteAcaoProposta?:'',
    iteFotoCamera?:'',
    iteFotoTermografica?:'',
    itePosHaviaFalha?:'',
    itePosHaviaFalhaObs?:'',
    itePosDiagnosticoFalha?:'',
    itePosDiagnosticoFalhaObs?:'',
    itePosTrabalhoAlem?:'',
    itePosTrabalhoAlemObs?:'',
    itePosDataIntervencao?:'',
    itePosTempoExecucao?:'',
    itePosResponsavel?:'',
    itePosNumeroOs?:'',
    itePosAvaliacaoIt?:'',
    iteDataAvaliacao?:'',
    iteStatus?:'',
    iteDataCriacao?:'',
    iteTipo?:'',
    iteFotoPainel?:'',
    iteFotoPainelDesc?:'',
    iteDataBaixa?:'',
    itePrazoExecucao?:'',
    iteEquipamentos?:'',
    iteTecnicoResponsavel?:'',
    iteNumeroOs?:'',
    iteCustoPreditiva?:'',
    iteCustoCorretiva?:'',
    iteQuebraEquipamento?:'',
    itePainelNumPortas?:'',
    medicao?: null,

}