export {useEmpresaService} from './empresa.service'
export {useMaquinaService} from './maquina.service'
export {useHistoricoComponenteService} from './historicoComponente.service'
export {useComponenteService} from './componente.service'
export {useMaquinaEquipamentoService} from './maquinaEquipamento.service'
export {useStatusSubComponenteService} from './statusSubComponente.service'
export {useComponentePecaService} from './componente_peca.service'
export { useSubComponenteService } from './sub_componente.service'
export { useComponente_Sub_ComponenteService } from './componente_subcomponente.service'
export { useMedicaoService } from './medicao.service'
export { useEquipamentoService } from './equipamento.service'
export { useInspecaoAcusticaLocalService } from './inspecao_acustica_local.service'
export { useRelatorioIntervencaoService } from './relatorio_intervencao.service'
export { useFalhaService } from './falha.service'
export { useMedicaoAnaliseVibracaoService } from './medicao_analise_vibracao.service'
export { useStatusComponenteVibracaoService } from './status_componente_vibracao.service'
export { useHistoricoComponenteVibracaoService } from './historico_componente_vibracao.service'
export { useInspecaoTermograficaService } from './inspecao_termografica.service'
export { useInspecaoTermograficaPecaService } from './inspecao_termografica_peca.service'
export { useCondicoesAmbienteService } from './condicoes_ambiente.service'
export { useEspecificacaoFalhaService } from './especificacao_falha.service'
export { useAnaliseOleoService } from './analise_oleo.service'
export { useMedicaoAnaliseOleoService } from './medicao_analise_oleo.service'
export { useStatusAnaliseOleoService } from './status_analise_oleo.service'
export { useMcaMedicaoService } from './mca_medicao.service'
export { useMcaRelatorioService } from './mca_relatorio.service'
export { useMcaCircuitoService } from './mca_circuito.service'
export { useMcaStatusRelatorioService } from './mca_status_relatorio.service'
export { useMcaStatusService } from './mca_status.service'
export { useCategoriaService } from './categoria.service'