export interface AnaliseOleo {

    anoCodigo?:'',
    anoNumero?:'',
    anoTecnico?:'',
    anoContaminacao?:'',
    anoDesgaste?:'',
    anoViscosidade?:'',
    anoObservacao?:'',
    anoNumeroDocumentoAnalise?:'',
    anoNumeroOs?:'',
    anoPosHaviaFalha?:'',
    anoPosHaviaFalhaObs?:'',
    anoPosDiagnosticoFalha?:'',
    anoPosDiagnosticoFalhaObs?:'',
    anoPosTrabalhoAlem?:'',
    anoPosTrabalhoAlemObs?:'',
    anoPosDataIntervencao?:'',
    anoPosTempoExecucao?:'',
    anoPosResponsavel?:'',
    anoPosAvaliado?:'',
    anoPosStatusAvaliacao?:'',
    anoPosBaixada?:'',
    anoPosBaixadaObservacao?:'',
    anoDateInsert?:'',
    anoUserInsert?:'',
    anoPosNumeroOs?:'',
    anoNomeArquivo?:'',
    anoArquivo?:'',
    medicao?: null,

}