export interface RelatorioIntervencao {

    riCodigo?:'',
    riFalha?:'',
    riEspecificacaoFalha?:'',
    riPosicao?:'',
    riAcaoProposta?:'',
    riEspectro?:'',
    riCurvaTendencia?:'',
    riVideo?:'',
    riStatus?:'',  
    riDataAbertura?:'',
    riDataColeta?:'',
    riFotoComponente?:'',
    riHaviaFalha?:'',
    riHaviaFalhaObs?:'',
    riDiagnosticoFalha?:'',
    riDiagnosticoFalhaObs?:'',
    riTrabalhoAlem?:'',
    riTrabalhoAlemObs?:'',
    riDataIntervencao?:'',
    riTempoExecucao?:'',
    riResponsavel?:'',
    riNumOs?:'',
    riStatusAvaliacao?:'',
    riAvaliado?:'',
    riBaixada?:'',
    riBaixadaObs?:'',
    riPrazoExecucao?:'',
    riCriticidade?:'',
    riEquipamentos?:'',
    riCategoria?:'',
    riNumeroOs?:'',
    riCustoPreditiva?:'',
    riCustoCorretiva?:'',
    riQuebraEquipamento?:'',
    inspecaoAcusticaLocal?: null

}